import { watchAuth, loginWithGoogle, loginWithEmail, logout, loadActiveStudents, loadStudentReport, QUESTION_IDS } from './firebase.js';
const $=s=>document.querySelector(s); const state={students:[],reports:new Map(),section:'11-A',user:null};
function setAuthMessage(t){$('#login-message').textContent=t||''} function showDashboard(s){$('#login-panel').hidden=s;$('#dashboard').hidden=!s}
function formatDate(ts){if(!ts)return'—';const d=ts.toDate?ts.toDate():new Date(ts.seconds?ts.seconds*1000:ts);return Number.isNaN(d.getTime())?'—':d.toLocaleString('es-CR',{dateStyle:'short',timeStyle:'short'})}
function formatTime(s){if(s===null||s===undefined||s==='')return'—';const n=Number(s);if(!Number.isFinite(n))return String(s);return n<60?`${n.toFixed(0)} s`:`${Math.floor(n/60)} min ${Math.round(n%60)} s`}
function qStatus(q,a){if(q?.completed)return['🟢','Completada'];if(q?.inProgress||a.length)return['🟡','En progreso'];return['⚪','Sin iniciar']}
function questionProgress(r,id){const q=r.questions[id]||{};return qStatus(q,r.attempts.filter(a=>a.questionId===id))}
function overallProgress(r){return Math.round(QUESTION_IDS.filter(id=>questionProgress(r,id)[1]==='Completada').length/QUESTION_IDS.length*100)}
async function loadSection(){ $('#students-loading').textContent=`Cargando estudiantes activos de ${state.section}…`;$('#students-body').innerHTML='';state.students=[];state.reports.clear();try{state.students=await loadActiveStudents(state.section);if(!state.students.length){$('#students-loading').textContent='No se encontraron estudiantes activos.';return}$('#students-loading').textContent=`${state.students.length} estudiantes activos`;for(const s of state.students){const r=await loadStudentReport(s.id);state.reports.set(s.id,r);renderStudentRow(s,r)}}catch(e){console.error(e);$('#students-loading').textContent='No fue posible consultar Firebase. Revisa Authentication y las Security Rules.'}}
function renderStudentRow(s,r){const tr=document.createElement('tr');const b=document.createElement('button');b.className='student-link';b.textContent=s.name;b.addEventListener('click',()=>showStudent(s));const td=document.createElement('td');td.appendChild(b);tr.appendChild(td);const p=document.createElement('td');p.textContent=`${overallProgress(r)}%`;tr.appendChild(p);QUESTION_IDS.forEach(id=>{const t=document.createElement('td');const [i,l]=questionProgress(r,id);t.className='status';t.title=l;t.textContent=i;tr.appendChild(t)});$('#students-body').appendChild(tr)}
function showStudent(s){const r=state.reports.get(s.id);if(!r)return;$('#student-name').textContent=s.name;$('#student-meta').textContent=`Sección ${state.section} · Progreso general ${overallProgress(r)}%`;const body=$('#attempts-body');body.innerHTML='';const rows=[...r.attempts].sort((a,b)=>(a.questionId+a.subquestionId+a.attemptNumber).localeCompare(b.questionId+b.subquestionId+b.attemptNumber,undefined,{numeric:true}));if(!rows.length)body.innerHTML='<tr><td colspan="8">No hay intentos registrados.</td></tr>';rows.forEach(a=>{const tr=document.createElement('tr');[a.questionId,a.subquestionId,a.answer??'—',a.correct?'✅':'❌',a.attemptNumber??'—',a.hintsUsed??0,a.score??'—',formatTime(a.timeSpent)].forEach((v,i)=>{const td=document.createElement('td');td.textContent=String(v);if(i===7)td.title=`Registrado: ${formatDate(a.createdAt)}`;tr.appendChild(td)});body.appendChild(tr)});$('#student-detail').hidden=false;$('#student-detail').scrollIntoView({behavior:'smooth',block:'start'})}
$('#email-login').addEventListener('submit',async e=>{e.preventDefault();setAuthMessage('Iniciando sesión…');try{await loginWithEmail($('#email').value.trim(),$('#password').value)}catch(error){console.error(error);setAuthMessage(`No fue posible iniciar sesión: ${error.code||error.message}`)}});
$('#login-google').addEventListener('click',async()=>{setAuthMessage('Abriendo acceso de Google…');try{await loginWithGoogle()}catch(error){console.error(error);setAuthMessage(`No fue posible iniciar sesión: ${error.code||error.message}`)}});
$('#logout').addEventListener('click',()=>logout());$('#section-select').addEventListener('change',e=>{state.section=e.target.value;loadSection()});$('#close-detail').addEventListener('click',()=>{$('#student-detail').hidden=true;window.scrollTo({top:0,behavior:'smooth'})});
watchAuth(async user=>{state.user=user||null;if(!user){$('#auth-status').textContent='No autenticado';showDashboard(false);return}if(user.isAnonymous){await logout();$('#auth-status').textContent='Acceso docente requerido';showDashboard(false);setAuthMessage('Esta aplicación requiere una cuenta docente.');return}$('#auth-status').textContent=user.email||'Docente autenticado';showDashboard(true);setAuthMessage('');await loadSection()});
